# version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data  # Maps the local postgres data directory to the container
    ports:
      - "5432:5432"

  pyspark:
    build:
      context: ./app
    depends_on:
      - postgres
    volumes:
      - ./app:/app
      - ./data/delta:/tmp/delta-table  # Maps the local delta data directory to the container
      - ./data/logs:/app/logs  # Maps the local logs directory to the container
    ports:
      - "8888:8888"