version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Use a local folder for persistence

  app:
    build:
      context: .
    container_name: python-postgres-app
    depends_on:
      - db  # Ensure db service starts first
    volumes:
      - ./logs:/app/logs  # Local logs folder
    environment:
      PYTHONUNBUFFERED: 1
    command: python /app/create_table.py
